uploads = []
generated = []

[[outputs]]
id = "xZYYAGMB73M85fbl0iSsj"
uri = "file://artifacts/filo-diretto-video/public/audio/vo_problem.mp3"
type = "audio"
title = "voiceover problem"

[[outputs]]
id = "3Y4hPEwM-S9AwEK2RjrW5"
uri = "file://artifacts/filo-diretto-video/public/audio/vo_intro.mp3"
type = "audio"
title = "voiceover intro"

[[outputs]]
id = "cyggqQ1eVkItCedLcIGMO"
uri = "file://artifacts/filo-diretto-video/public/audio/vo_dashboard.mp3"
type = "audio"
title = "voiceover dashboard"

[[outputs]]
id = "RWRRHj2CNM6aF-dfSE1TL"
uri = "file://artifacts/filo-diretto-video/public/audio/vo_wallet.mp3"
type = "audio"
title = "voiceover wallet"

[[outputs]]
id = "TvaE03zmhd9fauq6WeKYt"
uri = "file://artifacts/filo-diretto-video/public/audio/vo_push.mp3"
type = "audio"
title = "voiceover push"

[[outputs]]
id = "XW2rkiqExWGc4r2shUh0w"
uri = "file://artifacts/filo-diretto-video/public/audio/vo_analytics.mp3"
type = "audio"
title = "voiceover analytics"

[[outputs]]
id = "7xMGq0zfkJ0N2ohj2b-XI"
uri = "file://artifacts/filo-diretto-video/public/audio/vo_outro.mp3"
type = "audio"
title = "voiceover outro"

[[outputs]]
id = "6ba6hagqoX2fKGc9YDbNw"
uri = "file://artifacts/filo-diretto-video/public/audio/bg_music.mp3"
type = "audio"
title = "background music"

[[outputs]]
id = "3wCEW9nOj5eZD5RpbFQuE"
uri = "file://artifacts/filo-diretto-video/public/images/frustrated_hr.jpg"
type = "image"
title = "frustrated office worker at desk in front of laptop, modern office"

[[outputs]]
id = "43_iHyTc4xFgr2HF7IxKc"
uri = "file://artifacts/filo-diretto-video/public/images/happy_employee.jpg"
type = "image"
title = "smiling professional employee looking at smartphone in bright modern office"

[[outputs]]
id = "vhHPckdWI438CIKo_gtRG"
uri = "file://artifacts/filo-diretto-video/public/images/hand_phone.jpg"
type = "image"
title = "close up of hands holding modern smartphone on bright background"

[[outputs]]
id = "uuTyTeFikku_cDU2ZLsMC"
uri = "file://artifacts/filo-diretto-video/public/images/office_team.jpg"
type = "image"
title = "diverse team having a casual meeting in bright modern office"

[[outputs]]
id = "Kvb38_UFyj7rBqK4APNbj"
uri = "file://artifacts/filo-diretto-video/public/audio/vo_context.mp3"
type = "audio"
title = "vo context risorse umane"

[[outputs]]
id = "aN-uTn2IJrgHp8J8tVSZI"
uri = "file://artifacts/filo-diretto-video/public/audio/vo_push_new.mp3"
type = "audio"
title = "push vo programmabili"
